name: plant_app
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  animated_bottom_navigation_bar: ^1.2.0
  page_transition: ^2.0.9
  mobile_scanner: ^2.1.0
  flutter_launcher_icons: ^0.13.0
  get: ^4.6.5
  advance_notification: ^1.0.6
  simple_animations: ^4.0.1
  supercharged: ^2.1.1

dev_dependencies:
 flutter_test:
    sdk: flutter
 flutter_lints: ^2.0.0  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon/demo_icon.png"
  adaptive_icon_background: "#286E28"
  adaptive_icon_foreground: "assets/launcher_icon/demo_icon.png"

  


flutter:

  
  uses-material-design: true


  assets:
    - assets/images/

  fonts:
    - family: iranSans
      fonts:
        - asset: assets/fonts/Iranian Sans.ttf
    - family: LaleZar
      fonts:
        - asset: assets/fonts/Lalezar-Regular.ttf
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/YekanBakh-Regular.ttf

